import { createStyles } from 'antd-style';

export const useAdminSidebarStyles = createStyles(() => ({
  sidebar: {
    position: 'fixed',
    top: 0,
    left: 0,
    zIndex: 100,
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    color: 'var(--color-text-light)',
    background:
      'linear-gradient(180deg, color-mix(in srgb, var(--color-dark-teal) 94%, #000) 0%, var(--color-dark-teal) 65%, var(--color-teal) 100%)',
    borderRight: '0.0625rem solid color-mix(in srgb, var(--color-mint) 22%, transparent)',
    transition: 'width 0.25s ease, transform 0.25s ease',
    overflow: 'visible',
    '@media (max-width: 64rem)': {
      width: '17rem',
      zIndex: 110,
      borderRight: '0.0625rem solid color-mix(in srgb, var(--color-mint) 22%, transparent)',
      boxShadow: '0.5rem 0 2rem -1.25rem rgba(0, 0, 0, 0.45)',
    },
  },
  sidebarExpanded: {
    width: '17rem',
    '@media (max-width: 64rem)': {
      transform: 'translateX(0)',
    },
  },
  sidebarCollapsed: {
    width: '5.25rem',
    '@media (max-width: 64rem)': {
      width: '17rem',
      transform: 'translateX(-105%)',
    },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.25rem 1rem',
    borderBottom: '0.0625rem solid color-mix(in srgb, var(--color-mint) 20%, transparent)',
  },
  logo: {
    border: 'none',
    background: 'transparent',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    cursor: 'pointer',
    lineHeight: 0,
  },
  logoImage: {
    width: '1.1rem',
    height: 'auto',
    objectFit: 'contain',
    borderRadius: 0,
    background: 'transparent',
    padding: 0,
    display: 'block',
    transition: 'width 0.2s ease',
  },
  logoImageExpanded: {
    width: '10rem',

  },
  drawerToggle: {
    position: 'absolute',
    top: '5rem',
    right: '-0.7rem',
    width: '1.5rem',
    height: '1.5rem',
    borderRadius: '1rem',
    border: '0.0625rem solid color-mix(in srgb, var(--color-dark-teal) 22%, #d7dee0)',
    background: '#ffffff',
    color: 'var(--color-dark-teal)',
    display: 'grid',
    placeItems: 'center',
    fontSize: '0.7rem',
    cursor: 'pointer',
    boxShadow: '0 0.35rem 0.8rem -0.35rem rgba(0, 0, 0, 0.35)',
    transition: 'background 0.2s ease, color 0.2s ease, transform 0.2s ease',
    zIndex: 120,
    '&:hover': {
      background: 'var(--color-teal)',
      color: 'var(--color-text-light)',
      transform: 'scale(1.05)',
    },
    '@media (max-width: 64rem)': {
      display: 'none',
    },
  },
  drawerToggleCollapsed: {
    right: '-0.72rem',
  },
  nav: {
    flex: 1,
    overflowY: 'auto',
    padding: '1rem 0.75rem',
  },
  navSection: {
    '& + &': {
      marginTop: '1.1rem',
    },
  },
  navSectionCollapsed: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  navSectionTitle: {
    padding: '0 0.65rem',
    marginBottom: '0.5rem',
    fontSize: '0.72rem',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'color-mix(in srgb, var(--color-mint) 70%, #fff)',
  },
  navItem: {
    width: '100%',
    border: 'none',
    background: 'transparent',
    borderRadius: '0.7rem',
    color: 'var(--color-text-light)',
    padding: '0.68rem 0.7rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.65rem',
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'background 0.2s ease, transform 0.2s ease',
    '&:hover': {
      background: 'color-mix(in srgb, var(--color-mint) 18%, transparent)',
      transform: 'translateX(0.08rem)',
    },
    '& + &': {
      marginTop: '0.25rem',
    },
  },
  navItemCollapsed: {
    width: '2.75rem',
    height: '2.75rem',
    padding: 0,
    margin: '0 auto',
    borderRadius: '0.75rem',
    justifyContent: 'center',
    alignItems: 'center',
    '& + &': {
      marginTop: '0.45rem',
    },
  },
  navItemActive: {
    background: 'linear-gradient(135deg, color-mix(in srgb, var(--color-teal) 72%, #0a5052) 0%, var(--color-teal) 100%)',
    boxShadow: '0 0.5rem 1rem -0.65rem rgba(0, 0, 0, 0.6)',
  },
  navIcon: {
    width: '1.1rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
  },
  navIconActive: {
    color: 'var(--color-peach)',
  },
  navText: {
    fontSize: '0.92rem',
    fontWeight: 500,
    fontFamily: 'var(--font-primary)',
  },
  navTextActive: {
    color: 'var(--color-peach)',
  },
  navBadge: {
    marginLeft: 'auto',
    minWidth: '1.25rem',
    height: '1.25rem',
    borderRadius: '100vmax',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 0.35rem',
    fontSize: '0.68rem',
    fontWeight: 700,
    color: 'var(--color-dark-teal)',
    background: 'var(--color-light-peach)',
  },
  footer: {
    padding: '0.85rem 0.75rem 1rem',
    borderTop: '0.0625rem solid color-mix(in srgb, var(--color-mint) 22%, transparent)',
  },
  userCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    padding: '0.6rem',
    borderRadius: '0.75rem',
    background: 'color-mix(in srgb, var(--color-mint) 14%, transparent)',
  },
  userAvatar: {
    width: '2rem',
    height: '2rem',
    borderRadius: '0.6rem',
    display: 'grid',
    placeItems: 'center',
    color: 'var(--color-dark-teal)',
    background: 'var(--color-mint)',
  },
  userInfo: {
    minWidth: 0,
  },
  userName: {
    fontSize: '0.85rem',
    fontWeight: 600,
    color: 'var(--color-text-light)',
    lineHeight: 1.2,
  },
  userRole: {
    marginTop: '0.15rem',
    fontSize: '0.75rem',
    color: 'color-mix(in srgb, var(--color-mint) 75%, #fff)',
    lineHeight: 1.2,
  },
  logoutButton: {
    width: '100%',
    marginTop: '0.6rem',
    padding: '0.62rem 0.75rem',
    borderRadius: '0.65rem',
    border: '0.0625rem solid color-mix(in srgb, var(--color-mint) 28%, transparent)',
    background: 'transparent',
    color: 'var(--color-text-light)',
    fontSize: '0.84rem',
    fontWeight: 500,
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '0.45rem',
    cursor: 'pointer',
    transition: 'background 0.2s ease, border-color 0.2s ease',
    '&:hover': {
      background: 'color-mix(in srgb, #d93b3b 26%, transparent)',
      borderColor: 'color-mix(in srgb, #ff7f7f 45%, transparent)',
    },
  },
}));
