import { createStyles } from 'antd-style';

export const useProgrammesStyles = createStyles(() => ({
  programmesSection: {
    padding: '4rem 1.5rem 1rem',
    background: 'var(--background)',
  },
  container: {
    maxWidth: '75rem',
    margin: '0 auto',
    padding: '0 1rem',
  },
  header: {
    textAlign: 'center',
    maxWidth: '43.75rem',
    margin: '0 auto 4rem',
  },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    background: 'linear-gradient(135deg, rgba(44, 53, 49, 0.1) 0%, rgba(17, 100, 102, 0.1) 100%)',
    borderRadius: '3.125rem',
    padding: '0.5rem 1.25rem',
    marginBottom: '1.25rem',
    color: 'var(--color-dark-teal)',
    fontSize: '0.875rem',
    fontWeight: 600,
    border: '1px solid rgba(44, 53, 49, 0.2)',
  },
  title: {
    fontSize: 'clamp(2rem, 4vw, 3rem)',
    fontWeight: 800,
    color: 'var(--color-text-dark)',
    lineHeight: 1.2,
    marginBottom: '1rem',
    fontFamily: 'Outfit, sans-serif',
    '@media (max-width: 48rem)': { fontSize: 'clamp(1.5rem, 6vw, 2.5rem)' },
    '@media (max-width: 30rem)': { fontSize: 'clamp(1.25rem, 7vw, 2rem)' },
  },
  subtitle: {
    fontSize: '1.0625rem',
    color: 'var(--color-text-dark)',
    lineHeight: 1.7,
    '@media (max-width: 48rem)': { fontSize: '0.9375rem' },
    '@media (max-width: 30rem)': { fontSize: '0.875rem' },
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '2rem',
    '@media (max-width: 56.25rem)': { gridTemplateColumns: 'repeat(2, 1fr)' },
    '@media (max-width: 37.5rem)': { gridTemplateColumns: '1fr' },
  },
  card: {
    background: 'var(--color-teal)',
    borderRadius: '1.5rem',
    padding: '2.5rem 2rem',
    position: 'relative',
    overflow: 'hidden',
    transition: 'all 0.4s ease',
    border: '1px solid rgba(0, 0, 0, 0.04)',
    '&:hover': {
      transform: 'translateY(-0.5rem)',
      boxShadow: '0 1.5rem 3rem -0.75rem rgba(0,0,0,0.1)',
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '0.25rem',
      background: 'linear-gradient(90deg, var(--color-peach) 0%, var(--color-light-peach) 100%)',
      opacity: 0,
      transition: 'opacity 0.4s ease',
    },
    '&:hover::before': { opacity: 1 },
  },
  cardIcon: {
    background: 'var(--color-peach)',
    width: '4.5rem',
    height: '4.5rem',
    borderRadius: '1.25rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '2rem',
    marginBottom: '1.5rem',
    transition: 'all 0.4s ease',
  },
  cardTitle: {
    fontSize: '1.375rem',
    fontWeight: 700,
    color: 'var(--color-light-peach)',
    marginBottom: '0.75rem',
    fontFamily: 'Outfit, sans-serif',
  },
  cardDescription: {
    fontSize: '0.9375rem',
    color: 'var(--color-text-light)',
    lineHeight: 1.7,
    marginBottom: '1.5rem',
  },
  cardFeatures: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.625rem',
  },
  cardFeature: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
    fontSize: '0.875rem',
    color: 'var(--color-text-light)',
  },
  cardFeatureIcon: {
    color: 'var(--color-peach)',
    fontSize: '1rem',
  },
  cardLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginTop: '1.5rem',
    color: 'var(--color-peach)',
    fontWeight: 600,
    fontSize: '0.9375rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    '&:hover': {
      gap: '0.75rem',
      color: 'var(--color-light-peach)',
    },
  },
}));
