import { createStyles } from "antd-style";

export const useStyles = createStyles(() => ({
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '2rem',
    flexWrap: 'wrap' as const,
    gap: '1rem',
  },
  titleSection: {},
  title: {
    fontSize: '2rem',
    fontWeight: 800,
    color: '#1a1a2e',
    fontFamily: 'Outfit, sans-serif',
    marginBottom: '0.25rem',
  },
  subtitle: {
    fontSize: '0.9375rem',
    color: '#7a7a9a',
  },
  actions: {
    display: 'flex',
    gap: '1rem',
  },
  searchWrapper: {
    position: 'relative',
    width: '18rem',
    '@media (max-width: 768px)': {
      width: '100%',
    },
  },
  searchIcon: {
    position: 'absolute',
    left: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#7a7a9a',
    zIndex: 1,
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.75rem',
    border: '2px solid #e8e6e1',
    borderRadius: '0.75rem',
    fontSize: '0.9375rem',
    background: '#ffffff',
    transition: 'all 0.3s ease',
    '&:focus': {
      outline: 'none',
      borderColor: '#f7931e',
      boxShadow: '0 0 0 4px rgba(247, 147, 30, 0.1)',
    },
  },
  addButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1.5rem',
    background: 'linear-gradient(135deg, #f7931e 0%, #ff9800 100%)',
    border: 'none',
    borderRadius: '0.75rem',
    color: '#ffffff',
    fontSize: '0.9375rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 0.25rem 1rem -0.25rem rgba(247, 147, 30, 0.4)',
    '&:hover': {
      background: 'linear-gradient(135deg, #ff9800 0%, #ffc107 100%)',
      transform: 'translateY(-0.125rem)',
    },
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(20rem, 1fr))',
    gap: '1.5rem',
  },
  card: {
    background: '#ffffff',
    borderRadius: '1rem',
    boxShadow: '0 0.25rem 1.5rem -0.5rem rgba(0, 0, 0, 0.06)',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-0.25rem)',
      boxShadow: '0 0.5rem 2rem -0.5rem rgba(0, 0, 0, 0.1)',
    },
  },
  cardHeader: {
    padding: '1.5rem',
    borderBottom: '1px solid #f1f0ee',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
  },
  cardIcon: {
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '0.875rem',
    background: 'linear-gradient(135deg, #004d40 0%, #00695c 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    fontSize: '1.5rem',
    flexShrink: 0,
  },
  cardTitleSection: {
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    fontSize: '1.125rem',
    fontWeight: 700,
    color: '#1a1a2e',
    fontFamily: 'Outfit, sans-serif',
    marginBottom: '0.25rem',
  },
  cardInstructor: {
    fontSize: '0.875rem',
    color: '#7a7a9a',
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
  },
  statusBadge: {
    padding: '0.25rem 0.625rem',
    borderRadius: '1.25rem',
    fontSize: '0.6875rem',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.025em',
  },
  statusActive: {
    background: 'rgba(34, 197, 94, 0.15)',
    color: '#16a34a',
  },
  statusUpcoming: {
    background: 'rgba(59, 130, 246, 0.15)',
    color: '#2563eb',
  },
  statusCompleted: {
    background: 'rgba(156, 163, 175, 0.15)',
    color: '#6b7280',
  },
  cardBody: {
    padding: '1.5rem',
  },
  cardDescription: {
    fontSize: '0.875rem',
    color: '#5a5a7a',
    lineHeight: 1.6,
    marginBottom: '1rem',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
  },
  cardMeta: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '1rem',
    marginBottom: '1.25rem',
  },
  metaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    fontSize: '0.8125rem',
    color: '#7a7a9a',
  },
  progressSection: {
    marginBottom: '1rem',
  },
  progressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
  },
  progressLabel: {
    fontSize: '0.8125rem',
    color: '#7a7a9a',
  },
  progressValue: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#1a1a2e',
  },
  progressBar: {
    height: '0.5rem',
    background: '#f1f0ee',
    borderRadius: '0.25rem',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #f7931e 0%, #ffc107 100%)',
    borderRadius: '0.25rem',
    transition: 'width 0.3s ease',
  },
  cardActions: {
    display: 'flex',
    gap: '0.5rem',
    borderTop: '1px solid #f1f0ee',
    padding: '1rem 1.5rem',
  },
  actionButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    padding: '0.625rem',
    border: '2px solid #e8e6e1',
    borderRadius: '0.5rem',
    background: 'transparent',
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: '#5a5a7a',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      borderColor: '#f7931e',
      color: '#f7931e',
      background: 'rgba(247, 147, 30, 0.05)',
    },
  },
  deleteButton: {
    '&:hover': {
      borderColor: '#ef4444',
      color: '#ef4444',
      background: 'rgba(239, 68, 68, 0.05)',
    },
  },
}));