import { createStyles } from 'antd-style';

export const useAuthPageStyles = createStyles(() => ({
  wrapper: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #004d40 0%, #00695c 50%, #00796b 100%)',
    padding: '1.5rem',
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '-50%',
      right: '-20%',
      width: '60%',
      height: '150%',
      background: 'radial-gradient(circle, rgba(247, 147, 30, 0.15) 0%, transparent 60%)',
      pointerEvents: 'none',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: '-30%',
      left: '-10%',
      width: '50%',
      height: '100%',
      background: 'radial-gradient(circle, rgba(255, 193, 7, 0.1) 0%, transparent 50%)',
      pointerEvents: 'none',
    },
  },
  card: {
    width: '100%',
    maxWidth: '28rem',
    background: 'rgba(255, 255, 255, 0.98)',
    borderRadius: '1.5rem',
    padding: '3rem 2.5rem',
    boxShadow: '0 2rem 4rem -1rem rgba(0, 0, 0, 0.25)',
    position: 'relative',
    zIndex: 10,
    '@media (max-width: 600px)': {
      padding: '2rem 1.5rem',
    },
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    marginBottom: '2rem',
  },
  logoIcon: {
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '1rem',
    background: 'linear-gradient(135deg, #f7931e 0%, #ffc107 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    fontWeight: 800,
    color: '#ffffff',
    boxShadow: '0 0.5rem 1.5rem -0.25rem rgba(247, 147, 30, 0.4)',
  },
  logoText: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: '#1a1a2e',
    fontFamily: 'Outfit, sans-serif',
  },
  title: {
    textAlign: 'center' as const,
    fontSize: '1.75rem',
    fontWeight: 800,
    color: '#1a1a2e',
    marginBottom: '0.5rem',
    fontFamily: 'Outfit, sans-serif',
  },
  subtitle: {
    textAlign: 'center' as const,
    fontSize: '0.9375rem',
    color: '#5a5a7a',
    marginBottom: '2.5rem',
  },
  form: {
    '&& .ant-form-item-required::before': {
      display: 'none',
    },
    '&& .ant-form-item-required::after': {
      display: 'none',
    },
  },
  requiredMarkAsterisk: {
    color: '#ff4d4f',
    marginLeft: '0.25rem',
  },
  formGroup: {
    marginBottom: '1.25rem',
    '& .ant-form-item-label > label': {
      fontSize: '0.875rem',
      fontWeight: 600,
      color: '#1a1a2e',
      height: 'auto',
    },
    '& .ant-form-item-explain-error': {
      fontSize: '0.8125rem',
      marginTop: '0.375rem',
    },
  },
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#1a1a2e',
    marginBottom: '0.5rem',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputIcon: {
    color: '#7a7a9a',
    fontSize: '1.125rem',
    padding: '0 0.35rem 0 0.25rem',
    flexShrink: 0,
  },
  input: {
    '&.ant-input-affix-wrapper': {
      width: '100%',
      minHeight: '3.25rem',
      padding: '0 0.875rem',
      border: '2px solid #e8e6e1',
      borderRadius: '0.75rem',
      transition: 'all 0.3s ease',
      background: '#fdfcfa',
      boxShadow: 'none',
    },
    '&.ant-input-affix-wrapper .ant-input': {
      fontSize: '0.9375rem',
      fontFamily: 'inherit',
      background: 'transparent',
    },
    '&.ant-input-affix-wrapper .ant-input::placeholder': {
      color: '#a0a0b8',
    },
    '&.ant-input-affix-wrapper .ant-input-prefix': {
      color: '#7a7a9a',
      fontSize: '1.125rem',
      marginInlineEnd: '0.75rem',
    },
    '&.ant-input-affix-wrapper:hover': {
      borderColor: '#f7931e',
      background: '#ffffff',
    },
    '&.ant-input-affix-wrapper-focused, &.ant-input-affix-wrapper:focus-within': {
      borderColor: '#f7931e',
      background: '#ffffff',
      boxShadow: '0 0 0 4px rgba(247, 147, 30, 0.1)',
    },
    '& .ant-input-password-icon': {
      color: '#7a7a9a',
      fontSize: '1.125rem',
    },
    '& .ant-input-password-icon:hover': {
      color: '#f7931e',
    },
  },
  passwordToggle: {
    position: 'absolute',
    right: '1rem',
    color: '#7a7a9a',
    fontSize: '1.125rem',
    cursor: 'pointer',
    '&:hover': {
      color: '#f7931e',
    },
  },
  rememberRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '1.5rem',
  },
  rememberItem: {
    '&.ant-form-item': {
      marginBottom: 0,
    },
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.875rem',
    color: '#5a5a7a',
    cursor: 'pointer',
    '& .ant-checkbox-inner': {
      borderColor: '#c8c3b8',
      borderRadius: '0.25rem',
    },
    '&:hover .ant-checkbox-inner': {
      borderColor: '#f7931e',
    },
    '& .ant-checkbox-checked .ant-checkbox-inner': {
      borderColor: '#f7931e',
      backgroundColor: '#f7931e',
    },
  },
  checkbox: {
    width: '1.125rem',
    height: '1.125rem',
    accentColor: '#f7931e',
  },
  forgotLink: {
    fontSize: '0.875rem',
    color: '#f7931e',
    cursor: 'pointer',
    '&:hover': {
      color: '#004d40',
    },
  },
  submitButton: {
    '&.ant-btn': {
      width: '100%',
      height: '3.25rem',
      fontSize: '1rem',
      fontWeight: 600,
      borderRadius: '0.75rem',
      background: 'linear-gradient(135deg, #004d40 0%, #00695c 100%)',
      border: 'none',
      color: '#ffffff',
      boxShadow: '0 0.5rem 1.5rem -0.5rem rgba(0, 77, 64, 0.4)',
    },
    '&.ant-btn:not(:disabled):hover': {
      background: 'linear-gradient(135deg, #00695c 0%, #00796b 100%)',
      color: '#ffffff',
      border: 'none',
      transform: 'translateY(-0.125rem)',
    },
  },
  backLink: {
    textAlign: 'center' as const,
    marginTop: '2rem',
    fontSize: '0.875rem',
    color: '#5a5a7a',
  },
  backLinkAnchor: {
    color: '#f7931e',
    cursor: 'pointer',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  decorCircle1: {
    position: 'absolute',
    top: '-3rem',
    right: '-3rem',
    width: '8rem',
    height: '8rem',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, rgba(247, 147, 30, 0.2), rgba(255, 193, 7, 0.1))',
    zIndex: -1,
  },
  decorCircle2: {
    position: 'absolute',
    bottom: '-2rem',
    left: '-2rem',
    width: '6rem',
    height: '6rem',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, rgba(0, 105, 92, 0.15), rgba(0, 121, 107, 0.1))',
    zIndex: -1,
  },
}));
